// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dashboard.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDashboardStats = `-- name: GetDashboardStats :one
SELECT
  COALESCE(SUM(p.amount), 0)::text as total_revenue,
  COALESCE(SUM(r.number_of_seats), 0)::bigint as tickets_sold,
  COUNT(DISTINCT s.venue_id)::int as active_venues,
  (SELECT COUNT(*) FROM movies WHERE deleted_at IS NULL)::int as active_movies
FROM payments p
JOIN reservations r ON r.id = p.reservation_id
JOIN showtimes s ON s.id = r.showtime_id
WHERE p.payment_status = 'completed'
  AND r.deleted_at IS NULL
`

type GetDashboardStatsRow struct {
	TotalRevenue string `json:"total_revenue"`
	TicketsSold  int64  `json:"tickets_sold"`
	ActiveVenues int32  `json:"active_venues"`
	ActiveMovies int32  `json:"active_movies"`
}

func (q *Queries) GetDashboardStats(ctx context.Context) (GetDashboardStatsRow, error) {
	row := q.db.QueryRow(ctx, getDashboardStats)
	var i GetDashboardStatsRow
	err := row.Scan(
		&i.TotalRevenue,
		&i.TicketsSold,
		&i.ActiveVenues,
		&i.ActiveMovies,
	)
	return i, err
}

const getMonthlyRevenue = `-- name: GetMonthlyRevenue :many
SELECT
  DATE_TRUNC('month', p.paid_at)::date as month,
  COALESCE(SUM(p.amount), 0)::text as revenue
FROM payments p
WHERE p.payment_status = 'completed'
  AND p.paid_at >= DATE_TRUNC('month', NOW()) - INTERVAL '5 months'
GROUP BY DATE_TRUNC('month', p.paid_at)
ORDER BY month ASC
`

type GetMonthlyRevenueRow struct {
	Month   pgtype.Date `json:"month"`
	Revenue string      `json:"revenue"`
}

func (q *Queries) GetMonthlyRevenue(ctx context.Context) ([]GetMonthlyRevenueRow, error) {
	rows, err := q.db.Query(ctx, getMonthlyRevenue)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMonthlyRevenueRow{}
	for rows.Next() {
		var i GetMonthlyRevenueRow
		if err := rows.Scan(&i.Month, &i.Revenue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
