// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Movie struct {
	ID          int64              `json:"id"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	Runtime     int32              `json:"runtime"`
	Genre       string             `json:"genre"`
	AgeRating   string             `json:"age_rating"`
	Director    string             `json:"director"`
	PosterUrl   string             `json:"poster_url"`
	ReleaseDate pgtype.Date        `json:"release_date"`
	CreatedAt   time.Time          `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type Payment struct {
	ID            int64              `json:"id"`
	ReservationID int64              `json:"reservation_id"`
	Amount        pgtype.Numeric     `json:"amount"`
	PaymentMethod string             `json:"payment_method"`
	PaymentStatus string             `json:"payment_status"`
	TransactionID *string            `json:"transaction_id"`
	PaidAt        pgtype.Timestamptz `json:"paid_at"`
	CreatedAt     time.Time          `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
}

type Reservation struct {
	ID            int64              `json:"id"`
	ShowtimeID    int64              `json:"showtime_id"`
	UserID        uuid.UUID          `json:"user_id"`
	NumberOfSeats int32              `json:"number_of_seats"`
	TotalCost     pgtype.Numeric     `json:"total_cost"`
	Status        string             `json:"status"`
	ReservedAt    time.Time          `json:"reserved_at"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	ConfirmedAt   pgtype.Timestamptz `json:"confirmed_at"`
	CreatedAt     time.Time          `json:"created_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
}

type Seat struct {
	ID            int64              `json:"id"`
	ShowtimeID    int64              `json:"showtime_id"`
	RowLetter     string             `json:"row_letter"`
	SeatNumber    string             `json:"seat_number"`
	ReservationID *int64             `json:"reservation_id"`
	ReservedAt    pgtype.Timestamptz `json:"reserved_at"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	ConfirmedAt   pgtype.Timestamptz `json:"confirmed_at"`
	CreatedAt     time.Time          `json:"created_at"`
}

type Showtime struct {
	ID             int64              `json:"id"`
	MovieID        int64              `json:"movie_id"`
	StartTime      time.Time          `json:"start_time"`
	EndTime        time.Time          `json:"end_time"`
	AvailableSeats int32              `json:"available_seats"`
	PricePerSeat   pgtype.Numeric     `json:"price_per_seat"`
	VenueID        int32              `json:"venue_id"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

type User struct {
	ID              uuid.UUID          `json:"id"`
	Email           string             `json:"email"`
	TelephoneNumber *string            `json:"telephone_number"`
	PasswordHash    *string            `json:"password_hash"`
	FullName        string             `json:"full_name"`
	ProfileImageUrl *string            `json:"profile_image_url"`
	UserName        *string            `json:"user_name"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	VerifiedAt      pgtype.Timestamptz `json:"verified_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

type UserIdentity struct {
	ID             uuid.UUID `json:"id"`
	UserID         uuid.UUID `json:"user_id"`
	Provider       string    `json:"provider"`
	ProviderUserID string    `json:"provider_user_id"`
	CreatedAt      time.Time `json:"created_at"`
}

type Venue struct {
	ID         int32              `json:"id"`
	Name       string             `json:"name"`
	Address    string             `json:"address"`
	City       string             `json:"city"`
	TotalSeats int32              `json:"total_seats"`
	CreatedAt  time.Time          `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
}
