// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: showtimes.sql

package database

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createShowtime = `-- name: CreateShowtime :one
INSERT INTO showtimes (movie_id, start_time, end_time, available_seats, price_per_seat, venue_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, movie_id, start_time, end_time, available_seats, price_per_seat, venue_id, created_at, updated_at, deleted_at
`

type CreateShowtimeParams struct {
	MovieID        int64          `json:"movie_id"`
	StartTime      time.Time      `json:"start_time"`
	EndTime        time.Time      `json:"end_time"`
	AvailableSeats int32          `json:"available_seats"`
	PricePerSeat   pgtype.Numeric `json:"price_per_seat"`
	VenueID        int32          `json:"venue_id"`
}

func (q *Queries) CreateShowtime(ctx context.Context, arg CreateShowtimeParams) (Showtime, error) {
	row := q.db.QueryRow(ctx, createShowtime,
		arg.MovieID,
		arg.StartTime,
		arg.EndTime,
		arg.AvailableSeats,
		arg.PricePerSeat,
		arg.VenueID,
	)
	var i Showtime
	err := row.Scan(
		&i.ID,
		&i.MovieID,
		&i.StartTime,
		&i.EndTime,
		&i.AvailableSeats,
		&i.PricePerSeat,
		&i.VenueID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteShowtime = `-- name: DeleteShowtime :exec
UPDATE showtimes SET deleted_at = now() WHERE id = $1
`

func (q *Queries) DeleteShowtime(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteShowtime, id)
	return err
}

const getShowtimeById = `-- name: GetShowtimeById :one
SELECT id, movie_id, start_time, end_time, available_seats, price_per_seat, venue_id, created_at, updated_at, deleted_at FROM showtimes WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetShowtimeById(ctx context.Context, id int64) (Showtime, error) {
	row := q.db.QueryRow(ctx, getShowtimeById, id)
	var i Showtime
	err := row.Scan(
		&i.ID,
		&i.MovieID,
		&i.StartTime,
		&i.EndTime,
		&i.AvailableSeats,
		&i.PricePerSeat,
		&i.VenueID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getShowtimesAdmin = `-- name: GetShowtimesAdmin :many
SELECT s.id, s.movie_id, s.start_time, s.end_time, s.available_seats, s.price_per_seat, s.venue_id, s.created_at, s.updated_at, s.deleted_at, m.title as movie_title, v.name as venue_name
FROM showtimes s
JOIN movies m ON m.id = s.movie_id
JOIN venues v ON v.id = s.venue_id
WHERE s.deleted_at IS NULL
ORDER BY s.start_time DESC
LIMIT $1 OFFSET $2
`

type GetShowtimesAdminParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetShowtimesAdminRow struct {
	ID             int64              `json:"id"`
	MovieID        int64              `json:"movie_id"`
	StartTime      time.Time          `json:"start_time"`
	EndTime        time.Time          `json:"end_time"`
	AvailableSeats int32              `json:"available_seats"`
	PricePerSeat   pgtype.Numeric     `json:"price_per_seat"`
	VenueID        int32              `json:"venue_id"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
	MovieTitle     string             `json:"movie_title"`
	VenueName      string             `json:"venue_name"`
}

func (q *Queries) GetShowtimesAdmin(ctx context.Context, arg GetShowtimesAdminParams) ([]GetShowtimesAdminRow, error) {
	rows, err := q.db.Query(ctx, getShowtimesAdmin, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetShowtimesAdminRow{}
	for rows.Next() {
		var i GetShowtimesAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.MovieID,
			&i.StartTime,
			&i.EndTime,
			&i.AvailableSeats,
			&i.PricePerSeat,
			&i.VenueID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.MovieTitle,
			&i.VenueName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getShowtimesByMovie = `-- name: GetShowtimesByMovie :many
SELECT s.id, s.movie_id, s.start_time, s.end_time, s.available_seats, s.price_per_seat, s.venue_id, s.created_at, s.updated_at, s.deleted_at, v.name as venue_name, v.city as venue_city
FROM showtimes s
JOIN venues v ON v.id = s.venue_id
WHERE s.movie_id = $1
  AND s.start_time > now()
  AND s.deleted_at IS NULL
ORDER BY s.start_time ASC
`

type GetShowtimesByMovieRow struct {
	ID             int64              `json:"id"`
	MovieID        int64              `json:"movie_id"`
	StartTime      time.Time          `json:"start_time"`
	EndTime        time.Time          `json:"end_time"`
	AvailableSeats int32              `json:"available_seats"`
	PricePerSeat   pgtype.Numeric     `json:"price_per_seat"`
	VenueID        int32              `json:"venue_id"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
	VenueName      string             `json:"venue_name"`
	VenueCity      string             `json:"venue_city"`
}

func (q *Queries) GetShowtimesByMovie(ctx context.Context, movieID int64) ([]GetShowtimesByMovieRow, error) {
	rows, err := q.db.Query(ctx, getShowtimesByMovie, movieID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetShowtimesByMovieRow{}
	for rows.Next() {
		var i GetShowtimesByMovieRow
		if err := rows.Scan(
			&i.ID,
			&i.MovieID,
			&i.StartTime,
			&i.EndTime,
			&i.AvailableSeats,
			&i.PricePerSeat,
			&i.VenueID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.VenueName,
			&i.VenueCity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateShowtime = `-- name: UpdateShowtime :one
UPDATE showtimes SET
  start_time = COALESCE($1, start_time),
  end_time = COALESCE($2, end_time),
  available_seats = COALESCE($3, available_seats),
  price_per_seat = COALESCE($4, price_per_seat),
  venue_id = COALESCE($5, venue_id),
  updated_at = now()
WHERE id = $6 AND deleted_at IS NULL
RETURNING id, movie_id, start_time, end_time, available_seats, price_per_seat, venue_id, created_at, updated_at, deleted_at
`

type UpdateShowtimeParams struct {
	StartTime      pgtype.Timestamptz `json:"start_time"`
	EndTime        pgtype.Timestamptz `json:"end_time"`
	AvailableSeats *int32             `json:"available_seats"`
	PricePerSeat   pgtype.Numeric     `json:"price_per_seat"`
	VenueID        *int32             `json:"venue_id"`
	ID             int64              `json:"id"`
}

func (q *Queries) UpdateShowtime(ctx context.Context, arg UpdateShowtimeParams) (Showtime, error) {
	row := q.db.QueryRow(ctx, updateShowtime,
		arg.StartTime,
		arg.EndTime,
		arg.AvailableSeats,
		arg.PricePerSeat,
		arg.VenueID,
		arg.ID,
	)
	var i Showtime
	err := row.Scan(
		&i.ID,
		&i.MovieID,
		&i.StartTime,
		&i.EndTime,
		&i.AvailableSeats,
		&i.PricePerSeat,
		&i.VenueID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
