// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createLocalUser = `-- name: CreateLocalUser :one
INSERT INTO users(
    email, 
    telephone_number, 
    password_hash, 
    full_name, 
    auth_provider
) VALUES($1, $2, $3, $4, 'local') 
RETURNING id, email, telephone_number, password_hash, auth_provider, provider_user_id, full_name, profile_image_url, user_name, created_at, updated_at, verified_at, deleted_at
`

type CreateLocalUserParams struct {
	Email           string  `json:"email"`
	TelephoneNumber *string `json:"telephone_number"`
	PasswordHash    *string `json:"password_hash"`
	FullName        string  `json:"full_name"`
}

func (q *Queries) CreateLocalUser(ctx context.Context, arg CreateLocalUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createLocalUser,
		arg.Email,
		arg.TelephoneNumber,
		arg.PasswordHash,
		arg.FullName,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.TelephoneNumber,
		&i.PasswordHash,
		&i.AuthProvider,
		&i.ProviderUserID,
		&i.FullName,
		&i.ProfileImageUrl,
		&i.UserName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VerifiedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createOAuthUser = `-- name: CreateOAuthUser :one
INSERT INTO users(
    email, 
    full_name, 
    auth_provider, 
    provider_user_id,
    profile_image_url,
    verified_at  -- OAuth users are pre-verified by the provider
) VALUES($1, $2, $3, $4, $5, now()) 
RETURNING id, email, telephone_number, password_hash, auth_provider, provider_user_id, full_name, profile_image_url, user_name, created_at, updated_at, verified_at, deleted_at
`

type CreateOAuthUserParams struct {
	Email           string  `json:"email"`
	FullName        string  `json:"full_name"`
	AuthProvider    *string `json:"auth_provider"`
	ProviderUserID  *string `json:"provider_user_id"`
	ProfileImageUrl *string `json:"profile_image_url"`
}

func (q *Queries) CreateOAuthUser(ctx context.Context, arg CreateOAuthUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createOAuthUser,
		arg.Email,
		arg.FullName,
		arg.AuthProvider,
		arg.ProviderUserID,
		arg.ProfileImageUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.TelephoneNumber,
		&i.PasswordHash,
		&i.AuthProvider,
		&i.ProviderUserID,
		&i.FullName,
		&i.ProfileImageUrl,
		&i.UserName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VerifiedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT 
    id, email, telephone_number, full_name, 
    profile_image_url, user_name, auth_provider,
    created_at, updated_at, verified_at 
FROM users 
WHERE email = $1 AND deleted_at IS NULL
`

type GetUserByEmailRow struct {
	ID              uuid.UUID          `json:"id"`
	Email           string             `json:"email"`
	TelephoneNumber *string            `json:"telephone_number"`
	FullName        string             `json:"full_name"`
	ProfileImageUrl *string            `json:"profile_image_url"`
	UserName        *string            `json:"user_name"`
	AuthProvider    *string            `json:"auth_provider"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	VerifiedAt      pgtype.Timestamptz `json:"verified_at"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.TelephoneNumber,
		&i.FullName,
		&i.ProfileImageUrl,
		&i.UserName,
		&i.AuthProvider,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VerifiedAt,
	)
	return i, err
}

const getUserByProvider = `-- name: GetUserByProvider :one
SELECT 
    id, email, telephone_number, full_name, 
    profile_image_url, user_name, auth_provider,
    created_at, updated_at, verified_at 
FROM users 
WHERE auth_provider = $1 
  AND provider_user_id = $2 
  AND deleted_at IS NULL
`

type GetUserByProviderParams struct {
	AuthProvider   *string `json:"auth_provider"`
	ProviderUserID *string `json:"provider_user_id"`
}

type GetUserByProviderRow struct {
	ID              uuid.UUID          `json:"id"`
	Email           string             `json:"email"`
	TelephoneNumber *string            `json:"telephone_number"`
	FullName        string             `json:"full_name"`
	ProfileImageUrl *string            `json:"profile_image_url"`
	UserName        *string            `json:"user_name"`
	AuthProvider    *string            `json:"auth_provider"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	VerifiedAt      pgtype.Timestamptz `json:"verified_at"`
}

func (q *Queries) GetUserByProvider(ctx context.Context, arg GetUserByProviderParams) (GetUserByProviderRow, error) {
	row := q.db.QueryRow(ctx, getUserByProvider, arg.AuthProvider, arg.ProviderUserID)
	var i GetUserByProviderRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.TelephoneNumber,
		&i.FullName,
		&i.ProfileImageUrl,
		&i.UserName,
		&i.AuthProvider,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VerifiedAt,
	)
	return i, err
}
