// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outbox.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimEmailOutbox = `-- name: ClaimEmailOutbox :many
WITH candidates AS (
    SELECT id
    FROM email_outbox
    WHERE status = 'pending'
      AND (lease_expires_at IS NULL OR lease_expires_at < now())
    ORDER BY created_at
    FOR UPDATE SKIP LOCKED
    LIMIT $1
)
UPDATE email_outbox AS outbox
SET status = 'processing',
    lease_owner = $2,
    lease_expires_at = $3,
    attempt_count = attempt_count + 1,
    updated_at = now()
FROM candidates
WHERE outbox.id = candidates.id
RETURNING outbox.id, outbox.event_type, outbox.schema_version, outbox.aggregate_type, outbox.aggregate_id, outbox.recipient, outbox.template, outbox.payload, outbox.status, outbox.lease_owner, outbox.lease_expires_at, outbox.attempt_count, outbox.last_error, outbox.published_at, outbox.created_at, outbox.updated_at
`

type ClaimEmailOutboxParams struct {
	Limit          int32              `json:"limit"`
	LeaseOwner     *string            `json:"lease_owner"`
	LeaseExpiresAt pgtype.Timestamptz `json:"lease_expires_at"`
}

func (q *Queries) ClaimEmailOutbox(ctx context.Context, arg ClaimEmailOutboxParams) ([]EmailOutbox, error) {
	rows, err := q.db.Query(ctx, claimEmailOutbox, arg.Limit, arg.LeaseOwner, arg.LeaseExpiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmailOutbox{}
	for rows.Next() {
		var i EmailOutbox
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.SchemaVersion,
			&i.AggregateType,
			&i.AggregateID,
			&i.Recipient,
			&i.Template,
			&i.Payload,
			&i.Status,
			&i.LeaseOwner,
			&i.LeaseExpiresAt,
			&i.AttemptCount,
			&i.LastError,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createEmailOutbox = `-- name: CreateEmailOutbox :one
INSERT INTO email_outbox (
    id, event_type, schema_version, aggregate_type, aggregate_id,
    recipient, template, payload
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, event_type, schema_version, aggregate_type, aggregate_id, recipient, template, payload, status, lease_owner, lease_expires_at, attempt_count, last_error, published_at, created_at, updated_at
`

type CreateEmailOutboxParams struct {
	ID            uuid.UUID `json:"id"`
	EventType     string    `json:"event_type"`
	SchemaVersion int32     `json:"schema_version"`
	AggregateType string    `json:"aggregate_type"`
	AggregateID   string    `json:"aggregate_id"`
	Recipient     string    `json:"recipient"`
	Template      string    `json:"template"`
	Payload       []byte    `json:"payload"`
}

func (q *Queries) CreateEmailOutbox(ctx context.Context, arg CreateEmailOutboxParams) (EmailOutbox, error) {
	row := q.db.QueryRow(ctx, createEmailOutbox,
		arg.ID,
		arg.EventType,
		arg.SchemaVersion,
		arg.AggregateType,
		arg.AggregateID,
		arg.Recipient,
		arg.Template,
		arg.Payload,
	)
	var i EmailOutbox
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.SchemaVersion,
		&i.AggregateType,
		&i.AggregateID,
		&i.Recipient,
		&i.Template,
		&i.Payload,
		&i.Status,
		&i.LeaseOwner,
		&i.LeaseExpiresAt,
		&i.AttemptCount,
		&i.LastError,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markEmailOutboxPublished = `-- name: MarkEmailOutboxPublished :execrows
UPDATE email_outbox
SET status = 'published',
    published_at = now(),
    lease_owner = NULL,
    lease_expires_at = NULL,
    last_error = NULL,
    updated_at = now()
WHERE id = $1 AND lease_owner = $2 AND status = 'processing'
`

type MarkEmailOutboxPublishedParams struct {
	ID         uuid.UUID `json:"id"`
	LeaseOwner *string   `json:"lease_owner"`
}

func (q *Queries) MarkEmailOutboxPublished(ctx context.Context, arg MarkEmailOutboxPublishedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markEmailOutboxPublished, arg.ID, arg.LeaseOwner)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const releaseEmailOutbox = `-- name: ReleaseEmailOutbox :execrows
UPDATE email_outbox
SET status = 'pending',
    lease_owner = NULL,
    lease_expires_at = NULL,
    last_error = $3,
    updated_at = now()
WHERE id = $1 AND lease_owner = $2 AND status = 'processing'
`

type ReleaseEmailOutboxParams struct {
	ID         uuid.UUID `json:"id"`
	LeaseOwner *string   `json:"lease_owner"`
	LastError  *string   `json:"last_error"`
}

func (q *Queries) ReleaseEmailOutbox(ctx context.Context, arg ReleaseEmailOutboxParams) (int64, error) {
	result, err := q.db.Exec(ctx, releaseEmailOutbox, arg.ID, arg.LeaseOwner, arg.LastError)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
