// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: venues.sql

package dbgen

import (
	"context"
)

const createVenue = `-- name: CreateVenue :one
INSERT INTO venues (name, address, city, total_seats)
VALUES ($1, $2, $3, $4)
RETURNING id, name, address, city, total_seats, created_at, updated_at, deleted_at
`

type CreateVenueParams struct {
	Name       string `json:"name"`
	Address    string `json:"address"`
	City       string `json:"city"`
	TotalSeats int32  `json:"total_seats"`
}

func (q *Queries) CreateVenue(ctx context.Context, arg CreateVenueParams) (Venue, error) {
	row := q.db.QueryRow(ctx, createVenue,
		arg.Name,
		arg.Address,
		arg.City,
		arg.TotalSeats,
	)
	var i Venue
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.City,
		&i.TotalSeats,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getVenueById = `-- name: GetVenueById :one
SELECT id, name, address, city, total_seats, created_at, updated_at, deleted_at FROM venues WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetVenueById(ctx context.Context, id int32) (Venue, error) {
	row := q.db.QueryRow(ctx, getVenueById, id)
	var i Venue
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.City,
		&i.TotalSeats,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getVenues = `-- name: GetVenues :many
SELECT id, name, address, city, total_seats, created_at, updated_at, deleted_at FROM venues WHERE deleted_at IS NULL ORDER BY name
`

func (q *Queries) GetVenues(ctx context.Context) ([]Venue, error) {
	rows, err := q.db.Query(ctx, getVenues)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Venue{}
	for rows.Next() {
		var i Venue
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.City,
			&i.TotalSeats,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
