/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as PortalRouteRouteImport } from './routes/portal/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalSettingsRouteImport } from './routes/portal/settings'
import { Route as PortalSchedulingRouteImport } from './routes/portal/scheduling'
import { Route as PortalMoviesRouteImport } from './routes/portal/movies'
import { Route as PortalDashboardRouteImport } from './routes/portal/dashboard'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as PortalVenuesIndexRouteImport } from './routes/portal/venues/index'
import { Route as PortalVenuesNewRouteImport } from './routes/portal/venues/new'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRouteRoute = PortalRouteRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalSettingsRoute = PortalSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalSchedulingRoute = PortalSchedulingRouteImport.update({
  id: '/scheduling',
  path: '/scheduling',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalMoviesRoute = PortalMoviesRouteImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalDashboardRoute = PortalDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PortalRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const PortalVenuesIndexRoute = PortalVenuesIndexRouteImport.update({
  id: '/venues/',
  path: '/venues/',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalVenuesNewRoute = PortalVenuesNewRouteImport.update({
  id: '/venues/new',
  path: '/venues/new',
  getParentRoute: () => PortalRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/portal': typeof PortalRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/home': typeof AuthenticatedHomeRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/movies': typeof PortalMoviesRoute
  '/portal/scheduling': typeof PortalSchedulingRoute
  '/portal/settings': typeof PortalSettingsRoute
  '/portal/venues/new': typeof PortalVenuesNewRoute
  '/portal/venues/': typeof PortalVenuesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/portal': typeof PortalRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/home': typeof AuthenticatedHomeRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/movies': typeof PortalMoviesRoute
  '/portal/scheduling': typeof PortalSchedulingRoute
  '/portal/settings': typeof PortalSettingsRoute
  '/portal/venues/new': typeof PortalVenuesNewRoute
  '/portal/venues': typeof PortalVenuesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/portal': typeof PortalRouteRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/movies': typeof PortalMoviesRoute
  '/portal/scheduling': typeof PortalSchedulingRoute
  '/portal/settings': typeof PortalSettingsRoute
  '/portal/venues/new': typeof PortalVenuesNewRoute
  '/portal/venues/': typeof PortalVenuesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/portal'
    | '/login'
    | '/signup'
    | '/home'
    | '/portal/dashboard'
    | '/portal/movies'
    | '/portal/scheduling'
    | '/portal/settings'
    | '/portal/venues/new'
    | '/portal/venues/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/portal'
    | '/login'
    | '/signup'
    | '/home'
    | '/portal/dashboard'
    | '/portal/movies'
    | '/portal/scheduling'
    | '/portal/settings'
    | '/portal/venues/new'
    | '/portal/venues'
  id:
    | '__root__'
    | '/'
    | '/portal'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/home'
    | '/portal/dashboard'
    | '/portal/movies'
    | '/portal/scheduling'
    | '/portal/settings'
    | '/portal/venues/new'
    | '/portal/venues/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PortalRouteRoute: typeof PortalRouteRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/settings': {
      id: '/portal/settings'
      path: '/settings'
      fullPath: '/portal/settings'
      preLoaderRoute: typeof PortalSettingsRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/scheduling': {
      id: '/portal/scheduling'
      path: '/scheduling'
      fullPath: '/portal/scheduling'
      preLoaderRoute: typeof PortalSchedulingRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/movies': {
      id: '/portal/movies'
      path: '/movies'
      fullPath: '/portal/movies'
      preLoaderRoute: typeof PortalMoviesRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/dashboard': {
      id: '/portal/dashboard'
      path: '/dashboard'
      fullPath: '/portal/dashboard'
      preLoaderRoute: typeof PortalDashboardRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/portal/venues/': {
      id: '/portal/venues/'
      path: '/venues'
      fullPath: '/portal/venues/'
      preLoaderRoute: typeof PortalVenuesIndexRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/venues/new': {
      id: '/portal/venues/new'
      path: '/venues/new'
      fullPath: '/portal/venues/new'
      preLoaderRoute: typeof PortalVenuesNewRouteImport
      parentRoute: typeof PortalRouteRoute
    }
  }
}

interface PortalRouteRouteChildren {
  PortalDashboardRoute: typeof PortalDashboardRoute
  PortalMoviesRoute: typeof PortalMoviesRoute
  PortalSchedulingRoute: typeof PortalSchedulingRoute
  PortalSettingsRoute: typeof PortalSettingsRoute
  PortalVenuesNewRoute: typeof PortalVenuesNewRoute
  PortalVenuesIndexRoute: typeof PortalVenuesIndexRoute
}

const PortalRouteRouteChildren: PortalRouteRouteChildren = {
  PortalDashboardRoute: PortalDashboardRoute,
  PortalMoviesRoute: PortalMoviesRoute,
  PortalSchedulingRoute: PortalSchedulingRoute,
  PortalSettingsRoute: PortalSettingsRoute,
  PortalVenuesNewRoute: PortalVenuesNewRoute,
  PortalVenuesIndexRoute: PortalVenuesIndexRoute,
}

const PortalRouteRouteWithChildren = PortalRouteRoute._addFileChildren(
  PortalRouteRouteChildren,
)

interface AuthenticatedRouteChildren {
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PortalRouteRoute: PortalRouteRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
